2020-08-05 11:47:40,081 : WARNING :: Link timeout, no heartbeat in last 5 seconds
2020-08-05 11:48:05,053 : ERROR :: Exception in MAVLink input loop
Traceback (most recent call last):
  File "/home/abhish/anaconda3/envs/xbee/lib/python3.6/site-packages/dronekit/mavlink.py", line 211, in mavlink_thread_in
    fn(self)
  File "/home/abhish/anaconda3/envs/xbee/lib/python3.6/site-packages/dronekit/__init__.py", line 1371, in listener
    self._heartbeat_error)
dronekit.APIException: No heartbeat in 30 seconds, aborting.
